Repository Calciumdibromid/CaBr2, pull requests merged in 2021-02, with the labels that each got.

#70 add gestis parser
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/src/main.rs
  src-tauri/src/search/error.rs
  src-tauri/src/search/gestis/cmd.rs
  src-tauri/src/search/gestis/error.rs
  src-tauri/src/search/gestis/handler.rs
  src-tauri/src/search/gestis/mod.rs
  src-tauri/src/search/gestis/types.rs
  src-tauri/src/search/gestis/xml_parser.rs
  src-tauri/src/search/mod.rs
  src/app/core/services/chemical-info-service/chemicalInfo.model.ts
  src/app/core/services/chemical-info-service/chemicalInfo.service.ts
  src/debug-helper.ts
Labels: kind/getsis, rust

#82 updated tauri
  package.json
  yarn.lock
Labels: dependencies

#68 Add CI for js/ts linting
  .github/workflows/test.yml
Labels: kind/build, kind/testing, kind/ui

#67 README: add some desc & how to build/develop
  README.md
Labels: kind/docs

#103 Introduce .editorconfig
  .editorconfig
  .eslintrc.json
  .prettierrc.json
  src-tauri/rustfmt.toml
Labels: kind/docs

#112 medium big rewrite of SubstanceData
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/src/load_save/beryllium/mod.rs
  src-tauri/src/search/gestis/handler.rs
  src-tauri/src/search/gestis/types.rs
  src-tauri/src/search/gestis/xml_parser.rs
  src-tauri/src/types/mod.rs
  src/app/@core/services/substances/substances.model.ts
  src/debug-helper.ts
Labels: kind/refactor, rust

#121 Fix EditorConfig
  .editorconfig
Labels: kind/build, kind/docs

#123 Add Open/Save Dialogs
  src/app/menubar/menubar.component.ts
Labels: kind/feature, kind/ui

#102 CI: add backend linting & testing
  .github/workflows/test.yml
Labels: kind/build, kind/testing

#116 EStlint check import order
  .eslintrc.json
  src/app/@core/models/global.model.ts
  src/app/@core/services/loadSave/loadSave.service.ts
  src/app/@core/services/search/search.service.ts
  src/app/@core/services/tauri/tauri.service.ts
  src/app/app.component.spec.ts
  src/app/app.module.ts
  src/app/menubar/menubar.component.ts
  src/app/modules/MatModules.ts
  src/app/search/search-dialog/search-dialog.component.ts
  src/app/search/search.component.ts
  src/app/search/selected-search/selected-search.component.ts
  src/debug-helper.ts
  src/main.ts
  src/test.ts
Labels: kind/testing

#126 Fix extension filters & Set specific extension on save
  src-tauri/src/load_save/error.rs
  src-tauri/src/load_save/handler.rs
  src/app/menubar/menubar.component.ts
Labels: kind/bug, kind/ui, rust

#130 optimize binary in release mode
  src-tauri/Cargo.toml
Labels: kind/build

#133 added infos to cargo.toml
  src-tauri/Cargo.toml
Labels: kind/docs

#148 trigger search instead adding new search option when pressing enter
  src/app/search/search.component.html
  src/app/search/selected-search/selected-search.component.html
  src/app/search/selected-search/selected-search.component.ts
  yarn.lock
Labels: kind/bug, kind/ui

#156 Add Badges to README
  README.md
Labels: kind/docs

#145 Add command to get available file types
  src-tauri/src/load_save/cmd.rs
  src-tauri/src/load_save/handler.rs
  src-tauri/src/load_save/mod.rs
  src-tauri/src/load_save/types.rs
  src/app/@core/services/loadSave/loadSave.model.ts
  src/app/@core/services/loadSave/loadSave.service.ts
  src/app/menubar/menubar.component.html
  src/app/menubar/menubar.component.ts
Labels: kind/enhancement, rust

#158 added logic to ghs-symbol selection
  src/app/search/edit-search-results/edit-search-results.component.html
  src/app/search/edit-search-results/edit-search-results.component.scss
  src/app/search/edit-search-results/edit-search-results.component.ts
  yarn.lock
Labels: javascript, kind/enhancement, kind/ui

#120 Add Save to PDF
  .github/workflows/test.yml
  README.md
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/src/load_save/error.rs
  src-tauri/src/load_save/pdf/merge.rs
  src-tauri/src/load_save/pdf/mod.rs
  templates/first.html
  templates/second.html
  templates/styles.css
Labels: kind/feature

#111 Edit search results
  angular.json
  src-tauri/src/load_save/beryllium/mod.rs
  src-tauri/src/search/gestis/handler.rs
  src-tauri/src/search/gestis/xml_parser.rs
  src-tauri/src/types/mod.rs
  src/app/@core/models/global.model.ts
  src/app/@core/services/substances/substances.model.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/global-styles.scss
  src/app/header/header.component.html
  src/app/list-input-specifcations/list-input-specifcations.component.html
  src/app/modules/MatModules.ts
  src/app/preview/preview.component.html
  src/app/search/edit-search-results/edit-search-results.component.html
  src/app/search/edit-search-results/edit-search-results.component.scss
  src/app/search/edit-search-results/edit-search-results.component.spec.ts
  src/app/search/edit-search-results/edit-search-results.component.ts
  src/app/search/search-dialog/search-dialog.component.html
  src/app/search/search-dialog/search-dialog.component.scss
  src/app/search/search.component.html
  src/app/search/search.component.scss
  src/app/search/search.component.ts
  src/styles.scss
Labels: kind/feature, kind/ui

#151 [UI] Make Non User Text Unselectable
  src/app/header/header.component.html
  src/app/menubar/menubar.component.html
  src/app/preview/preview.component.html
  src/app/print-preview/print-preview.component.html
  src/app/search/edit-search-results/edit-search-results.component.html
  src/app/search/search.component.html
  src/styles.scss
Labels: kind/bug, kind/ui

#166 removed debug-helper script
  src/debug-helper.ts
  src/main.ts
Labels: kind/refactor

#167 moved paths of debug builds
  src-tauri/src/config/handler.rs
  src-tauri/src/config/mod.rs
Labels: kind/enhancement, rust

#168 added a feature to create portable builds
  src-tauri/Cargo.toml
  src-tauri/src/config/handler.rs
  src-tauri/src/config/mod.rs
Labels: kind/feature, rust

#175 default release builds are portable now
  src-tauri/Cargo.toml
Labels: kind/build

#178 [CI] Use own Worker for backend & update to node14
  .github/workflows/test.yml
Labels: kind/build, kind/testing

#176 changed background color for dialog components
  src/app/app.component.scss
  src/styles.scss
Labels: kind/ui

#177 Feature/alert snackbar
  src/app/@core/modules/MatModules.ts
  src/app/@core/modules/alert.module.ts
  src/app/@core/services/alertsnackbar/altersnackbar.model.ts
  src/app/@core/services/alertsnackbar/altersnackbar.service.ts
  src/app/alertsnackbar/alertsnackbar.component.html
  src/app/alertsnackbar/alertsnackbar.component.scss
  src/app/alertsnackbar/alertsnackbar.component.spec.ts
  src/app/alertsnackbar/alertsnackbar.component.ts
  src/app/app.component.html
  src/app/app.module.ts
  src/app/search/search.component.ts
  src/styles.scss
Labels: kind/feature, kind/ui

#179 [CI] use own docker image
  .github/workflows/test.yml
Labels: kind/build, kind/testing

#182 Gestis parser recognize cas number
  src-tauri/src/search/gestis/xml_parser.rs
Labels: kind/enhancement

#183 fixed path of portable builds
  src-tauri/src/config/handler.rs
Labels: kind/bug

#196 Stale Bot: ignore Pulls/Issues with label "reviewed" sticked to it
  .github/workflows/stale.yml
Labels: kind/build, kind/testing

#180 replaced most of the model with observables
  src-tauri/src/load_save/mod.rs
  src-tauri/src/search/gestis/xml_parser.rs
  src/app/@core/models/global.model.ts
  src/app/@core/modules/mat.modules.ts
  src/app/app.module.ts
  src/app/header/header.component.html
  src/app/header/header.component.ts
  src/app/list-input-specifcations/list-input-specifcations.component.html
  src/app/list-input-specifcations/list-input-specifcations.component.spec.ts
  src/app/list-input-specifcations/list-input-specifcations.component.ts
  src/app/menubar/menubar.component.html
  src/app/menubar/menubar.component.ts
  src/app/modifiable-string-list/modifiable-string-list.component.html
  src/app/modifiable-string-list/modifiable-string-list.component.scss
  src/app/modifiable-string-list/modifiable-string-list.component.spec.ts
  src/app/modifiable-string-list/modifiable-string-list.component.ts
  src/app/preview/preview.component.html
  src/app/preview/preview.component.ts
  src/app/search/edit-search-results/edit-search-results.component.html
  src/app/search/edit-search-results/edit-search-results.component.ts
  src/app/search/search.component.html
  src/app/search/search.component.ts
Labels: kind/bug, kind/enhancement, kind/refactor
