Repository Calciumdibromid/CaBr2, pull requests merged in 2021-05, with the labels that each got.

#368 [Translations] Add update script & example config
  .gitignore
  contrib/update-translation
  crowdin.example.yml
  translations/de_de.json
  translations/hr_hr.json
Labels: kind/build, kind/translation

#456 Add Contribution Guidelines
  CONTRIBUTING.md
Labels: kind/docs

#487 removed validator substancedata amount form
  src/app/edit-substance-data/edit-substance-data.component.html
  src/app/edit-substance-data/edit-substance-data.component.ts
Labels: kind/ui

#465 refactored unit model and added new units
  src-tauri/cabr2_load_save/src/pdf/types.rs
  src-tauri/cabr2_types/src/lib.rs
  src/app/@core/models/substances.model.ts
  src/app/edit-substance-data/edit-substance-data.component.html
  src/app/edit-substance-data/edit-substance-data.component.ts
  src/app/preview/preview.component.html
Labels: kind/enhancement, kind/refactor

#504 fixed units in preview
  src/app/preview/preview.component.html
  src/app/preview/preview.component.ts
Labels: kind/bug

#486 added export and save buttons below preview
  src-tauri/Cargo.toml
  src/app/menubar/menubar.component.html
  src/app/menubar/menubar.component.scss
  src/app/menubar/menubar.component.ts
Labels: kind/feature, kind/ui

#507 refactored plugins into features
  src-tauri/Cargo.toml
  src-tauri/cabr2_config/Cargo.toml
  src-tauri/cabr2_config/src/lib.rs
  src-tauri/cabr2_config/src/plugin.rs
  src-tauri/cabr2_load_save/Cargo.toml
  src-tauri/cabr2_load_save/src/cmd.rs
  src-tauri/cabr2_load_save/src/handler.rs
  src-tauri/cabr2_load_save/src/lib.rs
  src-tauri/cabr2_load_save/src/pdf/mod.rs
  src-tauri/cabr2_load_save/src/pdf/types.rs
  src-tauri/cabr2_load_save/src/plugin.rs
  src-tauri/cabr2_logger/src/lib.rs
  src-tauri/cabr2_logger/src/plugin.rs
  src-tauri/cabr2_search/Cargo.toml
  src-tauri/cabr2_search/src/cmd.rs
  src-tauri/cabr2_search/src/handler.rs
  src-tauri/cabr2_search/src/lib.rs
  src-tauri/cabr2_search/src/plugin.rs
  src-tauri/src/main.rs
  src-tauri/tauri.conf.json
Labels: kind/backend, kind/refactor

#521 fixed dev server and tauri build
  src-tauri/Cargo.toml
  src-tauri/tauri.conf.json
Labels: kind/backend, kind/bug, kind/build

#489 added provider tabs
  src/app/@core/modules/mat.modules.ts
  src/app/search/search-dialog/search-dialog.component.ts
  src/app/search/search.component.html
  src/app/search/search.component.ts
  src/app/search/selected-search/selected-search.component.html
  src/app/search/selected-search/selected-search.component.scss
  src/app/search/selected-search/selected-search.component.ts
Labels: kind/feature, kind/ui, technial debt

#528 optimized bp
  .prettierignore
  src/app/search/selected-search/selected-search.component.ts
  src/assets/bp/bp
  src/assets/bp/bp.js
  src/assets/bp/config.js
  src/assets/bp/config.json
Labels: kind/enhancement, kind/refactor, technial debt

#516 moved image sanitizing to global model
  src/app/@core/models/global.model.ts
  src/app/edit-substance-data/edit-substance-data.component.html
  src/app/edit-substance-data/edit-substance-data.component.ts
  src/app/preview/preview.component.html
  src/app/preview/preview.component.ts
Labels: kind/refactor, technial debt

#520 added reset button to edit substance data dialog
  src/app/@core/utils/compare.ts
  src/app/edit-substance-data/edit-substance-data.component.html
  src/app/edit-substance-data/edit-substance-data.component.scss
  src/app/edit-substance-data/edit-substance-data.component.ts
  translations/de_de.json
  translations/en_us.json
Labels: kind/feature, kind/ui

#530 fixed order of ghs symbols
  src/app/@core/models/global.model.ts
Labels: kind/ui

#529 make pipeline faster
  .github/workflows/backend.yml
  .github/workflows/frontend.yml
  .github/workflows/test.yml
Labels: kind/build

#531 Fix localization
  package.json
  src/app/@core/models/substances.model.ts
  src/app/@core/services/i18n/i18n.service.ts
  src/app/edit-substance-data/edit-substance-data.component.html
  src/app/edit-substance-data/edit-substance-data.component.ts
  src/assets/defaultStrings.json
  translations/en_us.json
  yarn.lock
Labels: kind/bug, kind/enhancement, kind/translation, kind/ui, technial debt

#541 rewrite of handlers
  src-tauri/cabr2_load_save/src/beryllium/mod.rs
  src-tauri/cabr2_load_save/src/cabr2/mod.rs
  src-tauri/cabr2_load_save/src/error.rs
  src-tauri/cabr2_load_save/src/handler.rs
  src-tauri/cabr2_load_save/src/pdf/mod.rs
  src-tauri/cabr2_load_save/src/plugin.rs
  src-tauri/cabr2_load_save/src/types.rs
Labels: kind/refactor

#560 CI: update-translations task commit & push to new branch
  .github/workflows/update-translations.yml
Labels: kind/bug, kind/build
