Repository Calciumdibromid/CaBr2, pull requests merged in 2021-09, with the labels that each got.

#756 Improve webserver
  src-tauri/Cargo.lock
  src-tauri/cabr2_config/src/handler.rs
  src-tauri/cabr2_config/src/webserver.rs
  src-tauri/cabr2_load_save/src/error.rs
  src-tauri/cabr2_load_save/src/handler.rs
  src-tauri/cabr2_load_save/src/plugin.rs
  src-tauri/cabr2_load_save/src/webserver.rs
  src-tauri/cabr2_logger/src/lib.rs
  src-tauri/cabr2_search/Cargo.toml
  src-tauri/cabr2_search/src/handler.rs
  src-tauri/cabr2_search/src/lib.rs
  src-tauri/cabr2_search/src/plugin.rs
  src-tauri/cabr2_search/src/webserver.rs
  src-tauri/cabr2_types/Cargo.toml
  src-tauri/cabr2_types/src/lib.rs
  src-tauri/cabr2_types/src/webserver.rs
Labels: kind/refactor, kind/backend

#798 Add Changelog Tool Config
  .changelog.yml
Labels: kind/docs

#797 Crowdin Update 2021-09-12
  translations/de_by.json
  translations/de_de.json
  translations/hr_hr.json
  translations/ru_ru.json
Labels: kind/translation

#800 re-add bug report button
  package.json
  src/app/app.module.ts
  src/app/components/bug-report-button/bug-report-button.component.html
  src/app/components/bug-report-button/bug-report-button.component.scss
  src/app/components/bug-report-button/bug-report-button.component.spec.ts
  src/app/components/bug-report-button/bug-report-button.component.ts
  src/app/components/report-bug/report-bug.component.html
  src/app/onepager/onepager.component.html
  src/app/onepager/onepager.component.scss
  translations/en_us.json
Labels: kind/bug

#801 Feature/replace selfmade localization with transloco
  angular.json
  package.json
  src/app/@core/models/global.model.ts
  src/app/@core/services/document/document.service.ts
  src/app/@core/services/i18n/i18n.interface.ts
  src/app/@core/services/i18n/i18n.service.ts
  src/app/@core/services/i18n/web/i18n.service.ts
  src/app/@core/services/provider/provider.interface.ts
  src/app/@core/services/provider/provider.service.ts
  src/app/@core/services/provider/web/provider.service.ts
  src/app/@core/services/service.module.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/components/bug-report-button/bug-report-button.component.scss
  src/app/components/consent/consent.component.html
  src/app/components/consent/consent.component.ts
  src/app/components/edit-substance-data/edit-substance-data.component.html
  src/app/components/edit-substance-data/edit-substance-data.component.ts
  src/app/components/export-buttons/export-buttons.component.html
  src/app/components/export-buttons/export-buttons.component.ts
  src/app/components/header/header.component.html
  src/app/components/header/header.component.ts
  src/app/components/manual/manual.component.html
  src/app/components/manual/manual.component.ts
  src/app/components/modifiable-string-list/modifiable-string-list.component.html
  src/app/components/modifiable-string-list/modifiable-string-list.component.ts
  src/app/components/navbar-menu/navbar-menu.component.html
  src/app/components/navbar-menu/navbar-menu.component.ts
  src/app/components/preview/preview.component.html
  src/app/components/preview/preview.component.ts
  src/app/components/report-bug/report-bug.component.html
  src/app/components/report-bug/report-bug.component.ts
  src/app/components/search/search-dialog/search-dialog.component.html
  src/app/components/search/search-dialog/search-dialog.component.ts
  src/app/components/search/search.component.html
  src/app/components/search/search.component.ts
  src/app/components/search/selected-search/selected-search.component.html
  src/app/components/search/selected-search/selected-search.component.ts
  src/app/components/security-things/security-things.component.html
  src/app/components/security-things/security-things.component.ts
  src/app/components/settings/settings.component.html
  src/app/components/settings/settings.component.ts
  src/app/components/yes-no-dialog/yes-no-dialog.component.html
  src/app/components/yes-no-dialog/yes-no-dialog.component.ts
  src/app/progress-dialog/progress-dialog.component.html
  src/app/progress-dialog/progress-dialog.component.ts
  src/app/transloco-root.module.ts
  src/assets/defaultStrings.json
  transloco.config.js
  yarn.lock
Labels: kind/enhancement, kind/refactor, kind/translation, kind/ui

#802 add angular splashscreen on app loading
  src/index.html
  src/styles.scss
Labels: kind/feature, kind/ui

#804 rm "format default strings" from pull translation script
  contrib/pull-translations
Labels: kind/build

#803 delete prompts
  prompts/assets/Logo_CaBr2.svg
  prompts/assets/screenshots_for_md/editor.png
  prompts/assets/screenshots_for_md/editor2.png
  prompts/assets/screenshots_for_md/filterselections_for_search.png
  prompts/assets/screenshots_for_md/search_1.png
  prompts/assets/screenshots_for_md/search_2.png
  prompts/consent-form.html
  prompts/getting-started.html
  prompts/telemetry.md
  src-tauri/cabr2_config/src/handler.rs
  src-tauri/cabr2_config/src/plugin.rs
  src-tauri/cabr2_config/src/webserver.rs
  src-tauri/src/webserver.rs
  src-tauri/tauri.conf.json
  src-wasm/Cargo.lock
  src-wasm/src/lib.rs
  src/app/@core/services/config/config.interface.ts
  src/app/@core/services/config/config.service.ts
  src/app/@core/services/config/web/config.service.ts
  src/app/@core/services/loadSave/web/loadSave.service.ts
  src/app/app.module.ts
  src/app/components/navbar-menu/navbar-menu.component.ts
  src/app/components/progress-dialog/progress-dialog.component.html
  src/app/components/progress-dialog/progress-dialog.component.scss
  src/app/components/progress-dialog/progress-dialog.component.spec.ts
  src/app/components/progress-dialog/progress-dialog.component.ts
Labels: kind/refactor

#813 Embed google fonts
  src/assets/fonts/material-icons/MaterialIcons-Regular.ttf
  src/assets/fonts/material-icons/MaterialIcons-Regular.woff
  src/assets/fonts/material-icons/MaterialIcons-Regular.woff2
  src/assets/fonts/material-icons/font.css
  src/assets/fonts/roboto/Roboto-Black.svg
  src/assets/fonts/roboto/Roboto-Black.ttf
  src/assets/fonts/roboto/Roboto-Black.woff
  src/assets/fonts/roboto/Roboto-Black.woff2
  src/assets/fonts/roboto/Roboto-BlackItalic.svg
  src/assets/fonts/roboto/Roboto-BlackItalic.ttf
  src/assets/fonts/roboto/Roboto-BlackItalic.woff
  src/assets/fonts/roboto/Roboto-BlackItalic.woff2
  src/assets/fonts/roboto/Roboto-Bold.svg
  src/assets/fonts/roboto/Roboto-Bold.ttf
  src/assets/fonts/roboto/Roboto-Bold.woff
  src/assets/fonts/roboto/Roboto-Bold.woff2
  src/assets/fonts/roboto/Roboto-BoldItalic.svg
  src/assets/fonts/roboto/Roboto-BoldItalic.ttf
  src/assets/fonts/roboto/Roboto-BoldItalic.woff
  src/assets/fonts/roboto/Roboto-BoldItalic.woff2
  src/assets/fonts/roboto/Roboto-Italic.svg
  src/assets/fonts/roboto/Roboto-Italic.ttf
  src/assets/fonts/roboto/Roboto-Italic.woff
  src/assets/fonts/roboto/Roboto-Italic.woff2
  src/assets/fonts/roboto/Roboto-Light.svg
  src/assets/fonts/roboto/Roboto-Light.ttf
  src/assets/fonts/roboto/Roboto-Light.woff
  src/assets/fonts/roboto/Roboto-Light.woff2
  src/assets/fonts/roboto/Roboto-LightItalic.svg
  src/assets/fonts/roboto/Roboto-LightItalic.ttf
  src/assets/fonts/roboto/Roboto-LightItalic.woff
  src/assets/fonts/roboto/Roboto-LightItalic.woff2
  src/assets/fonts/roboto/Roboto-Medium.svg
  src/assets/fonts/roboto/Roboto-Medium.ttf
  src/assets/fonts/roboto/Roboto-Medium.woff
  src/assets/fonts/roboto/Roboto-Medium.woff2
  src/assets/fonts/roboto/Roboto-MediumItalic.svg
  src/assets/fonts/roboto/Roboto-MediumItalic.ttf
  src/assets/fonts/roboto/Roboto-MediumItalic.woff
  src/assets/fonts/roboto/Roboto-MediumItalic.woff2
  src/assets/fonts/roboto/Roboto-Regular.svg
  src/assets/fonts/roboto/Roboto-Regular.ttf
  src/assets/fonts/roboto/Roboto-Regular.woff
  src/assets/fonts/roboto/Roboto-Regular.woff2
  src/assets/fonts/roboto/Roboto-Thin.svg
  src/assets/fonts/roboto/Roboto-Thin.ttf
  src/assets/fonts/roboto/Roboto-Thin.woff
  src/assets/fonts/roboto/Roboto-Thin.woff2
  src/assets/fonts/roboto/Roboto-ThinItalic.svg
  src/assets/fonts/roboto/Roboto-ThinItalic.ttf
  src/assets/fonts/roboto/Roboto-ThinItalic.woff
  src/assets/fonts/roboto/Roboto-ThinItalic.woff2
  src/assets/fonts/roboto/font.css
  src/index.html
Labels: kind/ui

#815 Add tooltips to navbar icons
  src/app/onepager/onepager.component.html
  translations/en_us.json
Labels: kind/ui

#821 Update Translation 2021-09-20
  translations/de_by.json
  translations/de_de.json
  translations/hr_hr.json
  translations/ru_ru.json
Labels: kind/translation

#825 Changelog v0.4.0
  CHANGELOG.md
Labels: kind/docs, skip-changelog

#826 Update Develop and Build instructions
  README.md
Labels: kind/docs
