Repository Calciumdibromid/CaBr2, pull requests merged in 2021-03, with the labels that each got.

#203 optimized build
  angular.json
  package.json
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/tauri.conf.json
  yarn.lock
Labels: kind/build

#208 fixed error when clicking abort
  src/app/search/edit-search-results/edit-search-results.component.ts
  src/app/search/search-dialog/search-dialog.component.html
  src/app/search/search-dialog/search-dialog.component.ts
  src/app/search/search.component.ts
  src/app/search/selected-search/selected-search.component.ts
Labels: kind/bug, kind/ui

#209 added gestis parsing for some values
  src-tauri/src/search/gestis/xml_parser.rs
Labels: kind/enhancement, kind/getsis

#217 improved logging, fixed #216
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/src/config/mod.rs
  src-tauri/src/load_save/mod.rs
  src-tauri/src/logger/cmd.rs
  src-tauri/src/logger/mod.rs
  src-tauri/src/main.rs
  src-tauri/src/search/gestis/mod.rs
  src-tauri/tauri.conf.json
  src/app/@core/utils/logger.ts
  src/app/app.component.ts
  src/app/menubar/menubar.component.ts
  src/app/search/search.component.ts
  src/main.ts
Labels: javascript, kind/backend, kind/bug, kind/enhancement, rust, windows

#221 "some" fixes:
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/src/config/mod.rs
  src-tauri/src/load_save/beryllium/mod.rs
  src-tauri/src/load_save/beryllium/types.rs
  src-tauri/src/search/gestis/xml_parser.rs
  src-tauri/src/types/mod.rs
  src/app/@core/services/substances/substances.model.ts
  src/app/menubar/menubar.component.html
  src/app/menubar/menubar.component.scss
  src/app/search/edit-search-results/edit-search-results.component.html
  src/assets/icons/arrow.svg
  src/assets/icons/flask.svg
  src/assets/icons/magnifier.svg
  src/assets/icons/menu.svg
  src/assets/icons/puzzle.svg
Labels: kind/bug, kind/enhancement

#224 Flat Badges
  README.md
  src-tauri/Cargo.toml
Labels: kind/docs

#226 refactor: moved each tauri-plugin to own rust-crate
  .github/workflows/test.yml
  contrib/for-each-cargo
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/cabr2_config/Cargo.toml
  src-tauri/cabr2_config/src/cmd.rs
  src-tauri/cabr2_config/src/error.rs
  src-tauri/cabr2_config/src/handler.rs
  src-tauri/cabr2_config/src/lib.rs
  src-tauri/cabr2_config/src/types.rs
  src-tauri/cabr2_load_save/Cargo.toml
  src-tauri/cabr2_load_save/src/beryllium/mod.rs
  src-tauri/cabr2_load_save/src/beryllium/types.rs
  src-tauri/cabr2_load_save/src/cabr2/mod.rs
  src-tauri/cabr2_load_save/src/cmd.rs
  src-tauri/cabr2_load_save/src/error.rs
  src-tauri/cabr2_load_save/src/handler.rs
  src-tauri/cabr2_load_save/src/lib.rs
  src-tauri/cabr2_load_save/src/pdf/merge.rs
  src-tauri/cabr2_load_save/src/pdf/mod.rs
  src-tauri/cabr2_load_save/src/types.rs
  src-tauri/cabr2_logger/Cargo.toml
  src-tauri/cabr2_logger/src/cmd.rs
  src-tauri/cabr2_logger/src/lib.rs
  src-tauri/cabr2_search/Cargo.toml
  src-tauri/cabr2_search/src/gestis/cmd.rs
  src-tauri/cabr2_search/src/gestis/error.rs
  src-tauri/cabr2_search/src/gestis/handler.rs
  src-tauri/cabr2_search/src/gestis/mod.rs
  src-tauri/cabr2_search/src/gestis/types.rs
  src-tauri/cabr2_search/src/gestis/xml_parser.rs
  src-tauri/cabr2_search/src/lib.rs
  src-tauri/cabr2_types/Cargo.toml
  src-tauri/cabr2_types/src/lib.rs
  src-tauri/cabr2_types/src/logging.rs
  src-tauri/src/main.rs
  src-tauri/src/search/mod.rs
Labels: kind/refactor, rust

#231 added logging and snackbar alerts for all service calls
  src/app/alertsnackbar/alertsnackbar.component.ts
  src/app/app.component.ts
  src/app/menubar/menubar.component.ts
  src/app/search/search-dialog/search-dialog.component.ts
  src/app/search/search.component.ts
  src/app/search/selected-search/selected-search.component.ts
Labels: kind/feature, kind/ui

#227 fixed infinite loading
  src/app/search/search-dialog/search-dialog.component.html
  src/app/search/search-dialog/search-dialog.component.scss
  src/app/search/search-dialog/search-dialog.component.ts
  src/app/search/search.component.ts
Labels: kind/bug, kind/ui

#228 added warning above preview
  src/app/preview/preview.component.html
  src/app/preview/preview.component.scss
  src/styles.scss
Labels: kind/enhancement, kind/ui

#237 enabled provider buttons
  src-tauri/Cargo.toml
  src-tauri/cabr2_search/src/gestis/handler.rs
  src-tauri/tauri.conf.json
  src/app/@core/services/tauri/tauri.service.ts
  src/app/search/search.component.html
  src/app/search/search.component.ts
Labels: kind/enhancement

#238 Remove unused print-preview
  src/app/app.module.ts
  src/app/menubar/menubar.component.html
  src/app/print-preview/print-preview.component.html
  src/app/print-preview/print-preview.component.scss
  src/app/print-preview/print-preview.component.spec.ts
  src/app/print-preview/print-preview.component.ts
Labels: kind/refactor, kind/ui

#155 Move Strings to json
  src/app/app.component.ts
  src/app/header/header.component.html
  src/app/header/header.component.ts
  src/app/menubar/menubar.component.html
  src/app/menubar/menubar.component.ts
  src/app/modifiable-string-list/modifiable-string-list.component.html
  src/app/modifiable-string-list/modifiable-string-list.component.ts
  src/app/preview/preview.component.html
  src/app/preview/preview.component.ts
  src/app/search/edit-search-results/edit-search-results.component.html
  src/app/search/edit-search-results/edit-search-results.component.ts
  src/app/search/search-dialog/search-dialog.component.html
  src/app/search/search-dialog/search-dialog.component.ts
  src/app/search/search.component.html
  src/app/search/search.component.ts
  src/app/search/selected-search/selected-search.component.html
  src/app/search/selected-search/selected-search.component.ts
  src/assets/descriptions.json
  src/assets/docsTemplate.json
  src/assets/strings.json
Labels: kind/enhancement, kind/refactor

#241 clean up alertservice and component, fixed weird alert behavior
  src/app/@core/modules/alert.module.ts
  src/app/@core/services/alertsnackbar/altersnackbar.model.ts
  src/app/@core/services/alertsnackbar/altersnackbar.service.ts
  src/app/alertsnackbar/alertsnackbar.component.html
  src/app/alertsnackbar/alertsnackbar.component.scss
  src/app/alertsnackbar/alertsnackbar.component.ts
  src/app/menubar/menubar.component.ts
  src/assets/strings.json
  src/styles.scss
Labels: kind/bug, kind/refactor

#246 fixed gestis xml_parser and typo in search-results
  src-tauri/cabr2_search/src/gestis/xml_parser.rs
  src/app/search/edit-search-results/edit-search-results.component.html
Labels: kind/backend, kind/bug

#250 fixed string name
  src/app/search/selected-search/selected-search.component.html
Labels: kind/bug

#253 added build task for frontend
  .github/workflows/test.yml
Labels: kind/build

#261 observables run only once and unsubscribe automatically to prevent weird behavior
  src/app/menubar/menubar.component.ts
Labels: javascript, kind/bug

#262 fixed template path
  src-tauri/cabr2_load_save/src/pdf/mod.rs
Labels: kind/bug

#260 added dynamic dialog and modified manual dialog a little bit
  src/app/app.module.ts
  src/app/manual/manual.component.html
  src/app/manual/manual.component.ts
  src/app/yes-no-dialog/yes-no-dialog.component.html
  src/app/yes-no-dialog/yes-no-dialog.component.scss
  src/app/yes-no-dialog/yes-no-dialog.component.spec.ts
  src/app/yes-no-dialog/yes-no-dialog.component.ts
Labels: javascript, kind/feature, kind/ui

#249 added first basic tests to xml_parser
  src-tauri/cabr2_search/assets/calcium.json
  src-tauri/cabr2_search/assets/cobaltdinitrat.json
  src-tauri/cabr2_search/src/gestis/xml_parser.rs
Labels: kind/testing, rust

#264 fixed infinite loading on error
  src/app/search/search-dialog/search-dialog.component.html
  src/app/search/search-dialog/search-dialog.component.ts
  src/assets/strings.json
Labels: kind/bug, kind/ui

#254 Localize
  README.md
  src-tauri/cabr2_config/src/cmd.rs
  src-tauri/cabr2_config/src/error.rs
  src-tauri/cabr2_config/src/handler.rs
  src-tauri/cabr2_config/src/lib.rs
  src-tauri/cabr2_config/src/types.rs
  src/app/@core/models/config.model.ts
  src/app/@core/models/global.model.ts
  src/app/@core/services/i18n/i18n.service.ts
  src/app/app.component.ts
  src/app/header/header.component.ts
  src/app/menubar/menubar.component.ts
  src/app/modifiable-string-list/modifiable-string-list.component.ts
  src/app/preview/preview.component.ts
  src/app/search/edit-search-results/edit-search-results.component.ts
  src/app/search/search-dialog/search-dialog.component.ts
  src/app/search/search.component.ts
  src/app/search/selected-search/selected-search.component.ts
  src/app/yes-no-dialog/yes-no-dialog.component.ts
  src/assets/defaultStrings.json
  translations/de_de.json
  translations/en_us.json
Labels: kind/translation

#269 Update English locales
  translations/en_us.json
Labels: kind/translation

#270 fixed some strings
  translations/de_de.json
  translations/en_us.json
Labels: kind/translation

#271 clear search field after adding substance
  src/app/search/search.component.ts
  src/app/search/selected-search/selected-search.component.ts
Labels: kind/enhancement, kind/ui

#272 Add Bavarian Locales
  translations/de_by.json
Labels: kind/translation

#275 move test assets into tests folder
  src-tauri/cabr2_search/src/gestis/xml_parser.rs
  src-tauri/cabr2_search/tests/assets/calcium.json
  src-tauri/cabr2_search/tests/assets/cobaltdinitrat.json
Labels: kind/refactor

#277 added missed translation strings
  src-tauri/cabr2_search/src/gestis/types.rs
  src/app/@core/services/search/search.model.ts
  src/app/@core/services/search/search.service.ts
  src/app/manual/manual.component.html
  src/app/manual/manual.component.ts
  src/app/menubar/menubar.component.html
  src/app/search/selected-search/selected-search.component.ts
  translations/de_de.json
Labels: kind/bug, kind/ui

#280 refactor frontend code to make prettier happy
  src/app/@core/interfaces/Header.ts
  src/app/@core/models/global.model.ts
  src/app/@core/modules/alert.module.ts
  src/app/@core/services/config/config.service.ts
  src/app/@core/services/i18n/i18n.service.ts
  src/app/@core/services/loadSave/loadSave.service.ts
  src/app/@core/services/search/search.service.ts
  src/app/@core/services/substances/substances.model.ts
  src/app/@core/services/substances/substances.service.ts
  src/app/@core/services/tauri/tauri.service.ts
  src/app/@core/utils/logger.ts
  src/app/alertsnackbar/alertsnackbar.component.spec.ts
  src/app/app.component.html
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/header/header.component.html
  src/app/header/header.component.scss
  src/app/header/header.component.spec.ts
  src/app/header/header.component.ts
  src/app/manual/manual.component.spec.ts
  src/app/manual/manual.component.ts
  src/app/menubar/menubar.component.spec.ts
  src/app/menubar/menubar.component.ts
  src/app/modifiable-string-list/modifiable-string-list.component.scss
  src/app/modifiable-string-list/modifiable-string-list.component.spec.ts
  src/app/modifiable-string-list/modifiable-string-list.component.ts
  src/app/preview/preview.component.html
  src/app/preview/preview.component.scss
  src/app/preview/preview.component.spec.ts
  src/app/preview/preview.component.ts
  src/app/search/edit-search-results/edit-search-results.component.html
  src/app/search/edit-search-results/edit-search-results.component.spec.ts
  src/app/search/edit-search-results/edit-search-results.component.ts
  src/app/search/search-dialog/search-dialog.component.spec.ts
  src/app/search/search-dialog/search-dialog.component.ts
  src/app/search/search.component.html
  src/app/search/search.component.spec.ts
  src/app/search/search.component.ts
  src/app/search/selected-search/selected-search.component.html
  src/app/search/selected-search/selected-search.component.spec.ts
  src/app/search/selected-search/selected-search.component.ts
  src/app/yes-no-dialog/yes-no-dialog.component.spec.ts
  src/app/yes-no-dialog/yes-no-dialog.component.ts
  src/assets/docsTemplate.json
  src/environments/environment.prod.ts
  src/environments/environment.ts
  src/index.html
  src/main.ts
  src/polyfills.ts
  src/styles.scss
  src/test.ts
Labels: kind/refactor, kind/ui

#282 Add version number of program and set it everywhere
  contrib/set-version
  src-tauri/Cargo.lock
  src-tauri/cabr2_config/Cargo.toml
  src-tauri/cabr2_config/src/cmd.rs
  src-tauri/cabr2_config/src/lib.rs
  src-tauri/cabr2_load_save/Cargo.toml
  src-tauri/cabr2_logger/Cargo.toml
  src-tauri/cabr2_search/Cargo.toml
  src-tauri/cabr2_search/src/gestis/mod.rs
  src-tauri/cabr2_types/Cargo.toml
Labels: kind/backend, kind/enhancement, rust

#292 added program version to config service
  src/app/@core/services/config/config.service.ts
  src/app/app.component.ts
Labels: kind/feature

#288 added settings dialog (#235)
  src-tauri/cabr2_config/src/cmd.rs
  src-tauri/cabr2_config/src/handler.rs
  src-tauri/cabr2_config/src/lib.rs
  src-tauri/cabr2_config/src/types.rs
  src-tauri/cabr2_logger/src/lib.rs
  src/app/@core/models/config.model.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/menubar/menubar.component.html
  src/app/menubar/menubar.component.ts
  src/app/settings/settings.component.html
  src/app/settings/settings.component.scss
  src/app/settings/settings.component.spec.ts
  src/app/settings/settings.component.ts
  translations/de_de.json
  translations/en_us.json
Labels: kind/feature, kind/ui

#295 rewrite of search service
  src-tauri/cabr2_search/src/cmd.rs
  src-tauri/cabr2_search/src/error.rs
  src-tauri/cabr2_search/src/gestis/handler.rs
  src-tauri/cabr2_search/src/gestis/mod.rs
  src-tauri/cabr2_search/src/gestis/types.rs
  src-tauri/cabr2_search/src/gestis/xml_parser.rs
  src-tauri/cabr2_search/src/handler.rs
  src-tauri/cabr2_search/src/lib.rs
  src-tauri/cabr2_search/src/types.rs
  src-tauri/src/main.rs
  src/app/@core/services/search/search.service.ts
  src/app/@core/services/substances/substances.service.spec.ts
  src/app/@core/services/substances/substances.service.ts
  src/app/search/search-dialog/search-dialog.component.ts
  src/app/search/search.component.ts
  src/app/search/selected-search/selected-search.component.ts
Labels: kind/backend, kind/enhancement, kind/refactor, rust

#298 fixed styling error on build
  src/app/preview/preview.component.scss
  src/app/search/search-dialog/search-dialog.component.scss
  src/styles.scss
  src/styles/color.scss
Labels: kind/build

#299 fixed weird deletion bug (#291)
  src/app/search/search.component.ts
Labels: javascript, kind/bug

#293 fixed preview, show ghs-symbols and phrases
  src/app/@core/pipes/molecularformula.pipe.ts
  src/app/app.module.ts
  src/app/preview/preview.component.html
  src/app/preview/preview.component.scss
  src/app/preview/preview.component.ts
  src/app/search/edit-search-results/edit-search-results.component.html
  translations/de_de.json
  translations/en_us.json
  tsconfig.json
Labels: kind/enhancement, kind/ui

#302 increased altertsnackbar time
  src/app/alertsnackbar/alertsnackbar.component.ts
Labels: kind/enhancement, kind/ui

#304 replaced space with no line breaking spaces
  src/app/preview/preview.component.ts
Labels: kind/ui

#303 CI: check code format
  .github/workflows/test.yml
  src/app/@core/services/substances/substances.service.ts
  src/app/app.component.ts
  src/app/preview/preview.component.html
  src/app/report-bug/report-bug.component.spec.ts
  src/app/search/search-dialog/search-dialog.component.ts
  src/app/settings/settings.component.scss
  src/app/settings/settings.component.spec.ts
  src/app/settings/settings.component.ts
  src/styles/color.scss
Labels: kind/build

#305 moved every non tauri stuff to handler
  src-tauri/cabr2_config/src/handler.rs
  src-tauri/cabr2_config/src/lib.rs
Labels: kind/refactor, rust

#287 fill pdf with data
  src-tauri/cabr2_config/src/lib.rs
  src-tauri/cabr2_load_save/src/beryllium/mod.rs
  src-tauri/cabr2_load_save/src/pdf/mod.rs
  src-tauri/cabr2_load_save/src/pdf/types.rs
  src-tauri/cabr2_search/src/gestis/mod.rs
  src-tauri/cabr2_types/src/lib.rs
  src/app/@core/services/substances/substances.model.ts
  src/app/preview/preview.component.ts
  src/app/search/edit-search-results/edit-search-results.component.ts
  templates/first.html
  templates/second.html
  templates/styles.css
Labels: kind/backend, kind/enhancement

#306 Translation Update
  translations/de_by.json
  translations/en_us.json
Labels: kind/translation

#307 clean up global model
  src/app/@core/models/global.model.ts
  src/app/search/search-dialog/search-dialog.component.ts
  src/app/search/search.component.ts
Labels: javascript, technial debt

#289 show getting started
  docs/consent-form.md
  prompts/assets/Logo_CaBr2.svg
  prompts/assets/screenshots_for_md/editor.png
  prompts/assets/screenshots_for_md/editor2.png
  prompts/assets/screenshots_for_md/filterselections_for_search.png
  prompts/assets/screenshots_for_md/search_1.png
  prompts/assets/screenshots_for_md/search_2.png
  prompts/consent-form.html
  prompts/getting-started.html
  prompts/getting-started.md
  prompts/telemetry.md
  src-tauri/cabr2_config/src/cmd.rs
  src-tauri/cabr2_config/src/error.rs
  src-tauri/cabr2_config/src/handler.rs
  src-tauri/cabr2_config/src/lib.rs
  src/app/@core/services/config/config.service.ts
  src/app/app.component.ts
  src/app/manual/manual.component.html
  src/app/manual/manual.component.scss
  src/app/manual/manual.component.ts
  src/app/menubar/menubar.component.ts
Labels: kind/feature, kind/ui

#308 disabled autofocus in edit search result dialog
  src/app/search/search.component.ts
Labels: javascript, kind/ui

#312 ok is disabled as long as no substance is selected
  src/app/search/search-dialog/search-dialog.component.html
Labels: kind/enhancement, kind/ui

#310 fixed edit search result modification check
  src/app/search/edit-search-results/edit-search-results.component.ts
Labels: kind/bug

#300 Feature/consent dialog
  src-tauri/cabr2_config/src/types.rs
  src/app/@core/models/config.model.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/consent/consent.component.html
  src/app/consent/consent.component.scss
  src/app/consent/consent.component.spec.ts
  src/app/consent/consent.component.ts
  src/app/menubar/menubar.component.ts
Labels: javascript, kind/feature, kind/ui, rust

#314 fixed styling import
  src/app/report-bug/report-bug.component.scss
Labels: kind/build

#315 bump version to 0.2.0
  src-tauri/Cargo.toml
  src-tauri/cabr2_config/Cargo.toml
  src-tauri/cabr2_load_save/Cargo.toml
  src-tauri/cabr2_logger/Cargo.toml
  src-tauri/cabr2_search/Cargo.toml
  src-tauri/cabr2_types/Cargo.toml
Labels: kind/docs

#316 fixed consent trigger
  src/app/app.component.ts
Labels: kind/bug

#331 fixed ci
  .github/workflows/test.yml
Labels: kind/build

#334 modified eslint options
  .eslintrc.json
  src/app/menubar/menubar.component.ts
Labels: kind/build

#324 Fix/search
  src-tauri/cabr2_search/src/gestis/mod.rs
Labels: kind/backend, kind/bug

#333 fixed config loading race conditions
  src/app/@core/models/config.model.ts
  src/app/app.component.ts
Labels: kind/ui

#325 Rewrote searchSearvice and added available provider endpoint
  src-tauri/cabr2_load_save/src/beryllium/mod.rs
  src-tauri/cabr2_search/src/cmd.rs
  src-tauri/cabr2_search/src/gestis/mod.rs
  src-tauri/cabr2_search/src/handler.rs
  src-tauri/cabr2_search/src/lib.rs
  src-tauri/cabr2_search/src/types.rs
  src/app/@core/models/global.model.ts
  src/app/@core/services/loadSave/loadSave.model.ts
  src/app/@core/services/provider/provider.model.ts
  src/app/@core/services/provider/provider.service.spec.ts
  src/app/@core/services/provider/provider.service.ts
  src/app/@core/services/provider/substances.model.ts
  src/app/@core/services/search/search.service.ts
  src/app/@core/services/substances/substances.service.spec.ts
  src/app/@core/services/substances/substances.service.ts
  src/app/preview/preview.component.ts
  src/app/search/edit-search-results/edit-search-results.component.ts
  src/app/search/search-dialog/search-dialog.component.ts
  src/app/search/search.component.html
  src/app/search/search.component.ts
  src/app/search/selected-search/selected-search.component.ts
  translations/de_de.json
Labels: kind/backend, kind/refactor, kind/ui

#348 log more and on a higher level
  src-tauri/cabr2_search/src/gestis/xml_parser.rs
Labels: kind/backend

#349 Restrict clippy
  .github/workflows/test.yml
  src-tauri/cabr2_load_save/src/beryllium/mod.rs
  src-tauri/cabr2_load_save/src/pdf/mod.rs
  src-tauri/cabr2_load_save/src/pdf/types.rs
Labels: kind/build

#338 added add-custom-substance button
  src-tauri/cabr2_load_save/src/beryllium/mod.rs
  src-tauri/cabr2_load_save/src/pdf/mod.rs
  src-tauri/cabr2_load_save/src/pdf/types.rs
  src-tauri/cabr2_search/src/gestis/mod.rs
  src-tauri/cabr2_search/src/gestis/types.rs
  src-tauri/cabr2_search/src/gestis/xml_parser.rs
  src-tauri/cabr2_types/src/lib.rs
  src/app/@core/pipes/molecularformula.pipe.ts
  src/app/@core/services/provider/substances.model.ts
  src/app/preview/preview.component.ts
  src/app/search/edit-search-results/edit-search-results.component.html
  src/app/search/edit-search-results/edit-search-results.component.ts
  src/app/search/search.component.html
  src/app/search/search.component.scss
  src/app/search/search.component.ts
  translations/de_de.json
  translations/en_us.json
Labels: javascript, kind/enhancement, kind/ui

#342 cleanup of docTemplate and addition of disposal defaults
  src/app/menubar/menubar.component.ts
  src/assets/docsTemplate.json
Labels: kind/ui, technial debt

#351 fixed menu icon resize bug
  prompts/consent-form.html
  prompts/getting-started.html
  prompts/getting-started.md
  src/app/manual/manual.component.scss
Labels: kind/bug, kind/ui

#354 added dots infront of list items
  src/app/modifiable-string-list/modifiable-string-list.component.html
  src/app/modifiable-string-list/modifiable-string-list.component.scss
Labels: kind/enhancement, kind/ui

#356 fixed style of section headings
  src/app/modifiable-string-list/modifiable-string-list.component.html
Labels: kind/enhancement, kind/ui

#359 removed mandatory empty line at the end of pdf
  src-tauri/cabr2_load_save/src/pdf/types.rs
  src/app/preview/preview.component.ts
Labels: kind/enhancement

#353 Feature/default unchanged popup
  src-tauri/cabr2_load_save/src/beryllium/mod.rs
  src-tauri/cabr2_search/src/gestis/mod.rs
  src-tauri/cabr2_types/src/lib.rs
  src/app/@core/models/global.model.ts
  src/app/@core/models/substances.model.ts
  src/app/@core/services/loadSave/loadSave.model.ts
  src/app/@core/services/provider/provider.service.ts
  src/app/@core/utils/compare.ts
  src/app/app.module.ts
  src/app/edit-substance-data/edit-substance-data.component.html
  src/app/edit-substance-data/edit-substance-data.component.scss
  src/app/edit-substance-data/edit-substance-data.component.spec.ts
  src/app/edit-substance-data/edit-substance-data.component.ts
  src/app/menubar/menubar.component.html
  src/app/menubar/menubar.component.ts
  src/app/preview/preview.component.ts
  src/app/search/search.component.html
  src/app/search/search.component.scss
  src/app/search/search.component.ts
  src/app/yes-no-dialog/yes-no-dialog.component.html
  src/app/yes-no-dialog/yes-no-dialog.component.scss
  src/app/yes-no-dialog/yes-no-dialog.component.ts
  translations/de_de.json
Labels: kind/bug, kind/feature, kind/ui

#357 improved styling and deleted "go brrrrr"
  src/app/menubar/menubar.component.html
  src/app/menubar/menubar.component.scss
Labels: kind/ui

#367 Update Locales from Crowdin
  translations/de_by.json
  translations/de_de.json
  translations/en_us.json
Labels: kind/translation

#391 fixed rust ci
  src-tauri/cabr2_config/src/lib.rs
  src-tauri/cabr2_load_save/src/lib.rs
  src-tauri/cabr2_search/src/lib.rs
  src-tauri/cabr2_types/src/lib.rs
Labels: kind/build

#398 bump ureq to 2.1.0
  src-tauri/Cargo.lock
  src-tauri/cabr2_search/Cargo.toml
  src-tauri/cabr2_search/src/error.rs
  src-tauri/cabr2_search/src/gestis/mod.rs
  src-tauri/cabr2_search/src/lib.rs
Labels: dependencies, kind/backend, kind/refactor

#392 Add drag and drop to substance data
  src/app/@core/modules/mat.modules.ts
  src/app/search/search.component.html
  src/app/search/search.component.scss
  src/app/search/search.component.ts
  translations/de_de.json
  translations/en_us.json
Labels: kind/feature, kind/ui

#405 fixes provider names in preview and pdf
  src-tauri/cabr2_load_save/src/lib.rs
  src-tauri/cabr2_load_save/src/pdf/mod.rs
  src-tauri/cabr2_search/src/lib.rs
  src-tauri/cabr2_types/src/lib.rs
  src-tauri/src/main.rs
  src/app/preview/preview.component.ts
Labels: kind/backend, kind/bug, kind/ui
