Repository Calciumdibromid/CaBr2, pull requests merged in 2021-04, with the labels that each got.

#406 Add tool to develop and debug gestis parser
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/cabr2_search/.gitignore
  src-tauri/cabr2_search/Cargo.toml
  src-tauri/cabr2_search/README.md
  src-tauri/cabr2_search/contrib/gestis/helper.rs
  src-tauri/cabr2_search/contrib/gestis_helper.sh
  src-tauri/cabr2_search/src/error.rs
  src-tauri/cabr2_search/src/gestis/mod.rs
  src-tauri/cabr2_search/src/gestis/types.rs
  src-tauri/cabr2_search/src/gestis/xml_parser.rs
  src-tauri/cabr2_search/src/handler.rs
  src-tauri/cabr2_search/src/lib.rs
Labels: kind/gestis

#441 fixed audit issues
  yarn.lock
Labels: dependencies

#457 Update from Crowdin
  translations/de_by.json
  translations/hr_hr.json
  translations/ru_ru.json
Labels: kind/translation

#443 migration to tauri beta
  .github/workflows/test.yml
  package.json
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/cabr2_config/Cargo.toml
  src-tauri/cabr2_config/src/cmd.rs
  src-tauri/cabr2_config/src/error.rs
  src-tauri/cabr2_config/src/lib.rs
  src-tauri/cabr2_load_save/Cargo.toml
  src-tauri/cabr2_load_save/src/cmd.rs
  src-tauri/cabr2_load_save/src/error.rs
  src-tauri/cabr2_load_save/src/handler.rs
  src-tauri/cabr2_load_save/src/lib.rs
  src-tauri/cabr2_load_save/src/types.rs
  src-tauri/cabr2_logger/Cargo.toml
  src-tauri/cabr2_logger/src/cmd.rs
  src-tauri/cabr2_logger/src/lib.rs
  src-tauri/cabr2_search/Cargo.toml
  src-tauri/cabr2_search/src/cmd.rs
  src-tauri/cabr2_search/src/error.rs
  src-tauri/cabr2_search/src/lib.rs
  src-tauri/src/main.rs
  src-tauri/tauri.conf.json
  src/app/@core/services/config/config.service.ts
  src/app/@core/services/i18n/i18n.service.ts
  src/app/@core/services/loadSave/loadSave.model.ts
  src/app/@core/services/loadSave/loadSave.service.ts
  src/app/@core/services/provider/provider.service.ts
  src/app/@core/services/tauri/tauri.service.ts
  src/app/@core/utils/logger.ts
  src/app/menubar/menubar.component.html
  src/app/menubar/menubar.component.ts
  yarn.lock
Labels: dependencies, rust

#461 make every file type a feature
  src-tauri/Cargo.toml
  src-tauri/cabr2_load_save/Cargo.toml
  src-tauri/cabr2_load_save/src/error.rs
  src-tauri/cabr2_load_save/src/lib.rs
Labels: kind/backend
