Repository Calciumdibromid/CaBr2, pull requests merged in 2022-02, with the labels that each got.

#1106 Remove unnecessary transloco object
  frontend/src/app/components/progress-dialog/progress-dialog.component.html
Labels: kind/refactor, technial debt

#1105 Fix log level filter
  crates/logger/src/lib.rs
Labels: kind/bug

#1109 Print all log messages in tauri also via `console.*` methods
  frontend/src/app/@core/utils/logger.ts
Labels: kind/bug

#1110 Fix logging message when saving file
  frontend/src/app/@core/services/document/document.service.ts
Labels: kind/bug

#1111 replace config-model hack with ngxs approach
  frontend/package.json
  frontend/src/app/@core/interfaces/config.interface.ts
  frontend/src/app/@core/models/config.model.ts
  frontend/src/app/@core/services/config/config.interface.ts
  frontend/src/app/@core/services/config/config.service.ts
  frontend/src/app/@core/services/config/web/config.service.ts
  frontend/src/app/@core/states/@states.ts
  frontend/src/app/@core/states/config.state.ts
  frontend/src/app/app.component.html
  frontend/src/app/app.component.ts
  frontend/src/app/app.module.ts
  frontend/src/app/components/navbar-menu/navbar-menu.component.ts
  frontend/src/app/components/settings/settings.component.ts
  frontend/src/app/onepager/onepager.component.html
  frontend/src/app/onepager/onepager.component.ts
  frontend/yarn.lock
Labels: kind/refactor, ui

#1116 change message for gestis disclaimer
  assets/translations/de_de.json
  assets/translations/en_us.json
Labels: kind/enhancement

#1117 move search icon to the beginning
  frontend/src/app/components/search/selected-search/selected-search.component.html
  frontend/src/app/components/search/selected-search/selected-search.component.scss
Labels: kind/refactor, ui

#1118 Destroy all Observables and fix bad code
  frontend/package.json
  frontend/src/app/@core/services/document/document.service.ts
  frontend/src/app/@core/services/loadSave/web/loadSave.service.ts
  frontend/src/app/components/bug-report-button/bug-report-button.component.ts
  frontend/src/app/components/edit-substance-data/edit-substance-data.component.ts
  frontend/src/app/components/header/header.component.ts
  frontend/src/app/components/loading/loading.component.ts
  frontend/src/app/components/manual/manual.component.ts
  frontend/src/app/components/modifiable-string-list/modifiable-string-list.component.ts
  frontend/src/app/components/progress-dialog/progress-dialog.component.ts
  frontend/src/app/components/report-bug/report-bug.component.ts
  frontend/src/app/components/search/search-dialog/search-dialog.component.ts
  frontend/src/app/components/search/search.component.ts
Labels: kind/refactor, technial debt

#1120 Update translations & pull-translations script
  assets/translations/de_by.json
  assets/translations/hr_hr.json
  assets/translations/ru_ru.json
  contrib/pull-translations
Labels: kind/translation

#1119 Changelog v0.5.0
  CHANGELOG.md
  frontend/package.json
  frontend/src-tauri/Cargo.lock
  frontend/src-tauri/Cargo.toml
  frontend/src-wasm/Cargo.lock
  frontend/src-wasm/Cargo.toml
  webserver/Cargo.lock
  webserver/Cargo.toml
Labels: kind/docs

#1127 Add migration of config in local storage
  frontend/src/main.ts
Labels: kind/bug

#1132 Add woodpecker and renovate configs
  .woodpecker/crates.yml
  .woodpecker/frontend.yml
  .woodpecker/tauri-app.yml
  .woodpecker/wasm-lib.yml
  .woodpecker/webserver.yml
  renovate.json
Labels: kind/ci, codeberg-migration
