Repository Calciumdibromid/CaBr2, pull requests merged in 2022-01, with the labels that each got.

#990 Add codespell into backend & frontend pipeline
  .github/workflows/backend.yml
  .github/workflows/frontend.yml
  README.md
  src/app/@core/services/loadSave/web/loadSave.service.ts
  src/app/components/edit-substance-data/edit-substance-data.component.ts
Labels: kind/ci

#1000 better no results message
  .github/workflows/frontend.yml
  src/app/components/search/search-dialog/search-dialog.component.html
  src/app/components/search/search-dialog/search-dialog.component.ts
  src/app/components/search/search.component.ts
  translations/en_us.json
Labels: ui

#1004 fix frontend custom unit
  src-tauri/cabr2_types/src/lib.rs
  src/app/@core/models/substances.model.ts
  src/app/components/edit-substance-data/edit-substance-data.component.html
  src/app/components/edit-substance-data/edit-substance-data.component.ts
  src/app/components/preview/preview.component.html
  src/app/components/preview/preview.component.ts
Labels: ui, backend

#1007 add error message to pdf dialog
  src/app/components/progress-dialog/progress-dialog.component.html
  src/app/components/progress-dialog/progress-dialog.component.scss
  src/app/components/progress-dialog/progress-dialog.component.ts
  translations/en_us.json
Labels: ui-web

#1006 some style improvements
  src/app/components/modifiable-string-list/modifiable-string-list.component.html
  src/app/components/modifiable-string-list/modifiable-string-list.component.scss
  src/app/components/search/search.component.html
  src/app/components/search/search.component.scss
Labels: ui

#1005 let dependabot run cargo on complete repo
  .github/dependabot.yml
Labels: kind/ci

#1008 update translations
  translations/de_by.json
  translations/de_de.json
  translations/hr_hr.json
  translations/ru_ru.json
Labels: kind/translation

#1011 Add Changelog for v0.4.1
  CHANGELOG.md
Labels: kind/docs, skip-changelog

#1020 bump rust edition to 2021
  crates/config/Cargo.toml
  crates/load_save/Cargo.toml
  crates/logger/Cargo.toml
  crates/rustfmt.toml
  crates/search/Cargo.toml
  frontend/src-tauri/Cargo.toml
  frontend/src-tauri/rustfmt.toml
  frontend/src-wasm/Cargo.toml
  frontend/src-wasm/rustfmt.toml
Labels: kind/build, rust

#1024 Update dependabot.yml
  .github/dependabot.yml
Labels: kind/ci, skip-changelog

#1023 remove version reqirement from config handler
  crates/config/Cargo.toml
  crates/search/src/handler.rs
  frontend/src-tauri/Cargo.lock
  frontend/src-tauri/src/impls/search.rs
  frontend/src-wasm/src/impls/search.rs
  webserver/Cargo.lock
  webserver/src/impls/search.rs
Labels: kind/refactor, technial debt, backend

#1029 Add every rust project to dependabot config
  .github/dependabot.yml
Labels: dependencies, kind/ci, skip-changelog

#1028 Wrap RwLock to simplify code
  crates/load_save/Cargo.toml
  crates/load_save/src/handler.rs
  crates/search/Cargo.toml
  crates/search/src/handler.rs
  crates/types/Cargo.toml
  crates/types/src/lib.rs
  crates/types/src/lock.rs
  frontend/src-tauri/Cargo.lock
  frontend/src-wasm/Cargo.lock
  webserver/Cargo.lock
Labels: kind/refactor, technial debt

#1031 Migrate angular to 13
  frontend/.gitignore
  frontend/package.json
  frontend/src/app/app.component.ts
  frontend/src/app/components/bug-report-button/bug-report-button.component.scss
  frontend/src/app/components/edit-substance-data/edit-substance-data.component.ts
  frontend/src/app/components/modifiable-string-list/modifiable-string-list.component.scss
  frontend/src/app/components/modifiable-string-list/modifiable-string-list.component.ts
  frontend/src/app/components/navbar-menu/navbar-menu.component.scss
  frontend/src/app/components/preview/preview.component.scss
  frontend/src/app/components/report-bug/report-bug.component.scss
  frontend/src/app/components/scrollbutton/scrollbutton.component.scss
  frontend/src/app/components/search/search-dialog/search-dialog.component.scss
  frontend/src/app/components/search/search.component.scss
  frontend/src/polyfills.ts
  frontend/src/styles.scss
  frontend/src/styles/color.scss
  frontend/src/test.ts
  frontend/yarn.lock
Labels: dependencies

#1036 Improve READMEs and IntelliJ support
  .idea/CaBr2.iml
  README.md
  frontend/README.md
  frontend/src-wasm/README.md
  webserver/README.md
Labels: kind/docs

#1037 Feature/airbnb style guide
  CaBr2.code-workspace
  frontend/.eslintrc.json
  frontend/.prettierrc.json
  frontend/package.json
  frontend/src/app/@core/models/config.model.ts
  frontend/src/app/@core/models/global.model.ts
  frontend/src/app/@core/models/substances.model.ts
  frontend/src/app/@core/services/alertsnackbar/altersnackbar.model.ts
  frontend/src/app/@core/services/document/document.service.ts
  frontend/src/app/@core/services/loadSave/web/loadSave.service.ts
  frontend/src/app/@core/services/provider/provider.interface.ts
  frontend/src/app/@core/services/provider/provider.service.ts
  frontend/src/app/@core/services/provider/web/provider.service.ts
  frontend/src/app/@core/utils/compare.ts
  frontend/src/app/@core/utils/logger.ts
  frontend/src/app/app.component.ts
  frontend/src/app/components/alertsnackbar/alertsnackbar.component.ts
  frontend/src/app/components/edit-substance-data/edit-substance-data.component.ts
  frontend/src/app/components/loading/loading.component.ts
  frontend/src/app/components/preview/preview.component.ts
  frontend/src/app/components/progress-dialog/progress-dialog.component.ts
  frontend/src/app/components/search/search-dialog/search-dialog.component.ts
  frontend/src/app/components/search/search.component.ts
  frontend/src/app/components/search/selected-search/selected-search.component.ts
  frontend/src/app/components/settings/settings.component.ts
  frontend/yarn.lock
Labels: kind/refactor, ui, technial debt

#1044 [bugfix] add .gitattributes file to force lf on checkout
  .gitattributes
Labels: kind/bug

#1041 rename ureq to request in config
  crates/config/src/types.rs
  crates/logger/src/lib.rs
Labels: kind/refactor, backend

#1051 New error handling in crates
  crates/load_save/src/beryllium/error.rs
  crates/load_save/src/beryllium/mod.rs
  crates/load_save/src/cabr2/error.rs
  crates/load_save/src/cabr2/mod.rs
  crates/load_save/src/error.rs
  crates/load_save/src/pdf/error.rs
  crates/load_save/src/pdf/merge.rs
  crates/load_save/src/pdf/mod.rs
  crates/search/src/error.rs
  crates/search/src/gestis/error.rs
  crates/search/src/gestis/mod.rs
  crates/search/src/gestis/xml_parser.rs
  crates/search/src/handler.rs
  frontend/src-tauri/Cargo.lock
  frontend/src-wasm/Cargo.lock
  frontend/src-wasm/src/lib.rs
  webserver/Cargo.lock
Labels: kind/refactor

#1053 Add tests
  .github/workflows/crates.yml
  crates/search/src/gestis/mod.rs
  crates/search/src/gestis/types.rs
  crates/search/src/gestis/xml_parser.rs
  crates/search/tests/assets/bananenöl.json
  crates/search/tests/assets/wasser.json
Labels: kind/refactor, kind/testing

#1077 Fix wasm-bindgen
  frontend/src-wasm/Cargo.lock
  frontend/src-wasm/Cargo.toml
Labels: dependencies, kind/upstream

#1076 Fix clippy in ci
  .github/workflows/crates.yml
  .github/workflows/tauri-app-rust.yml
  .github/workflows/wasm-lib.yml
  .github/workflows/webserver.yml
Labels: kind/ci

#1060 Gestis parser rewrite
  CaBr2.code-workspace
  crates/logger/src/lib.rs
  crates/search/Cargo.toml
  crates/search/contrib/gestis/helper.rs
  crates/search/contrib/gestis_helper.sh
  crates/search/src/gestis/error.rs
  crates/search/src/gestis/functions.rs
  crates/search/src/gestis/mod.rs
  crates/search/src/gestis/tests.rs
  crates/search/src/gestis/types.rs
  crates/search/src/gestis/xml_parser.rs
  crates/search/tests/assets/cobaltdinitrat.json
  crates/search/tests/assets/wasser.json
  crates/search/tests/assets/wasserglas.json
  crates/search/tests/assets/wasserstoffperoxid.json
  frontend/src-tauri/Cargo.lock
  frontend/src-wasm/Cargo.lock
  webserver/Cargo.lock
Labels: kind/refactor

#1090 Changed alterSnackbar to alert snackbar
  frontend/src/app/@core/services/alertsnackbar/alertsnackbar.model.ts
  frontend/src/app/@core/services/alertsnackbar/alertsnackbar.service.ts
  frontend/src/app/@core/services/document/document.service.ts
  frontend/src/app/app.component.ts
  frontend/src/app/components/alertsnackbar/alertsnackbar.component.ts
  frontend/src/app/components/search/search-dialog/search-dialog.component.ts
  frontend/src/app/components/search/search.component.ts
  frontend/src/app/components/search/selected-search/selected-search.component.ts
Labels: kind/refactor, ui

#1048 Introduce NGXS
  frontend/package.json
  frontend/src/app/@core/actions/disposal.actions.ts
  frontend/src/app/@core/actions/human-and-environment-danger.actions.ts
  frontend/src/app/@core/actions/in-case-of-danger.actions.ts
  frontend/src/app/@core/actions/rules-of-conduct-acitons.ts
  frontend/src/app/@core/interfaces/Header.ts
  frontend/src/app/@core/interfaces/string-list-state-model.interface.ts
  frontend/src/app/@core/models/global.model.ts
  frontend/src/app/@core/models/header.model.ts
  frontend/src/app/@core/models/substances.model.ts
  frontend/src/app/@core/operators/string-list-operators.ts
  frontend/src/app/@core/services/config/config.interface.ts
  frontend/src/app/@core/services/config/config.service.ts
  frontend/src/app/@core/services/config/web/config.service.ts
  frontend/src/app/@core/services/document/document.service.ts
  frontend/src/app/@core/services/loadSave/loadSave.model.ts
  frontend/src/app/@core/services/provider/provider.service.ts
  frontend/src/app/@core/services/provider/web/provider.service.ts
  frontend/src/app/@core/services/service.module.ts
  frontend/src/app/@core/states/@generic.state.ts
  frontend/src/app/@core/states/@states.ts
  frontend/src/app/@core/states/disposal.state.ts
  frontend/src/app/@core/states/ghs-symbols.state.ts
  frontend/src/app/@core/states/header.state.ts
  frontend/src/app/@core/states/human-and-environment-danger.state.ts
  frontend/src/app/@core/states/incase-of-danger.state.ts
  frontend/src/app/@core/states/rules-of-conduct.state.ts
  frontend/src/app/@core/states/substance-data.state.ts
  frontend/src/app/@core/utils/action-newable.ts
  frontend/src/app/@core/utils/forms.helper.ts
  frontend/src/app/app.component.ts
  frontend/src/app/app.module.ts
  frontend/src/app/components/edit-substance-data/edit-substance-data.component.html
  frontend/src/app/components/edit-substance-data/edit-substance-data.component.ts
  frontend/src/app/components/header/header.component.html
  frontend/src/app/components/header/header.component.ts
  frontend/src/app/components/modifiable-string-list/modifiable-string-list.component.html
  frontend/src/app/components/modifiable-string-list/modifiable-string-list.component.scss
  frontend/src/app/components/modifiable-string-list/modifiable-string-list.component.ts
  frontend/src/app/components/modifiable-string-list/text-area-field/text-area-field.component.html
  frontend/src/app/components/modifiable-string-list/text-area-field/text-area-field.component.scss
  frontend/src/app/components/modifiable-string-list/text-area-field/text-area-field.component.spec.ts
  frontend/src/app/components/modifiable-string-list/text-area-field/text-area-field.component.ts
  frontend/src/app/components/navbar-menu/navbar-menu.component.ts
  frontend/src/app/components/preview/preview.component.html
  frontend/src/app/components/preview/preview.component.ts
  frontend/src/app/components/search/search.component.ts
  frontend/src/app/components/security-things/security-things.component.html
  frontend/src/app/components/security-things/security-things.component.ts
  frontend/src/app/ngxs.config.ts
  frontend/yarn.lock
Labels: kind/feature, kind/refactor

#1096 Fix unit translation
  frontend/src/app/components/edit-substance-data/edit-substance-data.component.html
  frontend/src/app/components/edit-substance-data/edit-substance-data.component.ts
Labels: kind/bug

#1099 complete remove of e2e
  frontend/e2e/protractor.conf.js
  frontend/e2e/src/app.e2e-spec.ts
  frontend/e2e/src/app.po.ts
  frontend/e2e/tsconfig.json
  frontend/package.json
  frontend/yarn.lock
Labels: dependencies

#1098 force three symbols in each row in preview
  frontend/src/app/components/preview/preview.component.html
  frontend/src/app/components/preview/preview.component.scss
Labels: kind/enhancement, ui

#1095 update contrib scripts
  contrib/for-each-cargo
  contrib/push-translations
  contrib/set-version
  contrib/settings
Labels: kind/build
